#!/usr/bin/env bash
# Check if CityGisProcess is running
if pgrep "CityGisProcess" > /dev/null
then
    printf "CityGisProcess module is already running at $(date +%d-%m-%Y)!\n" &> log
else
    cd ../bin
    ./CityGisProcess_d &
    cd ../../public/
fi

