#!/usr/bin/env bash
# Check if CityGisProcess is running
if pgrep "CityGisProcess_" > /dev/null
then
    printf "CityGisProcess module is not running at $(date +%d-%m-%Y)..."
    return;
else
    printf "CityGisProcess module is already running at $(date +%d-%m-%Y)!"
    cd ../bin
    ./CityGisProcess_d
    cd ../../public/
fi

