<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p class="text-center">
                    &copy; {{Carbon\Carbon::now()->year}} Project56. Report generated by the CityGis app.
                </p>
            </div>
        </div>
    </div>
</footer>
<!--/#footer-->
